using Polars, Test, Dates, Tables, Statistics

include("fixtures.jl")

@testset "Polars.jl" begin
    include("aqua.jl")

    include("dataframe/construction.jl")
    include("dataframe/gc.jl")
    include("dataframe/io.jl")
    include("dataframe/describe.jl")

    include("lazyframe/lazy_vs_eager.jl")
    include("lazyframe/scan_parquet.jl")
    include("lazyframe/scan_csv.jl")
    include("lazyframe/sink_parquet.jl")
    include("lazyframe/sink_csv.jl")
    include("lazyframe/sink_ipc.jl")
    include("lazyframe/scan_ipc.jl")
    include("lazyframe/head.jl")
    include("lazyframe/collect_schema.jl")

    include("operations/select_with_columns.jl")
    include("operations/filter.jl")
    include("operations/sort.jl")
    include("operations/join.jl")
    include("operations/concat.jl")
    include("operations/group_by.jl")
    include("operations/group_by_dynamic.jl")
    include("operations/empty.jl")
    include("operations/frame_verbs.jl")
    include("operations/unique.jl")
    include("operations/reshape.jl")

    include("expr/literals_cast.jl")
    include("expr/arithmetic.jl")
    include("expr/aggregation.jl")
    include("expr/naming.jl")
    include("expr/null_handling.jl")
    include("expr/lit_vector.jl")
    include("expr/statistics.jl")
    include("expr/over.jl")
    include("expr/when_then_otherwise.jl")
    include("expr/order_window.jl")
    include("expr/math.jl")
    include("expr/horizontal.jl")
    include("expr/replace.jl")
    include("expr/sort_top_k.jl")
    include("expr/is_unique_dup.jl")
    include("expr/sample.jl")
    include("expr/curried_forms.jl")
    include("expr/selectors.jl")
    include("expr/meta.jl")

    include("datatypes/strings.jl")
    include("datatypes/datetimes.jl")
    include("datatypes/times.jl")
    include("datatypes/durations.jl")
    include("datatypes/timezones.jl")
    include("datatypes/lists.jl")
    include("datatypes/structs.jl")
    include("datatypes/series.jl")
    include("datatypes/binary.jl")
    include("datatypes/list_struct_write.jl")

    include("misc.jl")
    include("misc_ffi_safety.jl")
end
