[[libpolars]]
arch = "aarch64"
git-tree-sha1 = "8d0ac87b8c861c4207f89bbc48189bb5825b8fcf"
os = "macos"

    [[libpolars.download]]
    sha256 = "8f601df637a238daae021e33efaa10e89c3d7a6a2f9015c1b60090da1fc8f1f8"
    url = "https://github.com/ymiftah/Polars.jl/releases/download/libpolars-v0.5.0/libpolars.v0.5.0.aarch64-apple-darwin.tar.gz"
[[libpolars]]
arch = "x86_64"
git-tree-sha1 = "4f61364dbbfedb9ddca18bb52c3caeef4b5f7de6"
libc = "glibc"
os = "linux"

    [[libpolars.download]]
    sha256 = "deca5756d0577ca07ad1f97dcfe85e50c40ec0353a7fe24455d0d9ae6f1dd87f"
    url = "https://github.com/ymiftah/Polars.jl/releases/download/libpolars-v0.5.0/libpolars.v0.5.0.x86_64-linux-gnu.tar.gz"