module API

# Generated by Clang.jl from c-polars/include/polars.h — do not hand-edit.
# Regenerate with `julia --project=gen gen/generate.jl` from the repo root.
include("./generated.jl")

end # module
